version: '3.8'
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    # this is to allow ping 
    privileged: true 
    volumes:
      - ./data:/app/data
    ports:
      - "4001:3001"  # <Host Port>:<Container Port>
      # - "3307:3306"

